baseURL = "https://www.pragmaxim.com/"
title = "Pragmaxim"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
theme = "pragmaxim-theme"

# Languages
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  [languages.cs]
    languageName = "Čeština"
    languageCode = "cs-cz"
    weight = 2
    [[languages.cs.menu.header]]
      name = "Zkušenosti"
      URL = "#experience"
      weight = 1

    [[languages.cs.menu.header]]
      name = "Blog"
      URL = "#blog"
      weight = 2

    [[languages.cs.menu.header]]
      name = "Portfolio"
      URL = "#portfolio"
      weight = 3

    [[languages.cs.menu.header]]
      name = "Kontakt"
      URL = "#contact"
      weight = 4

    [[languages.cs.menu.footer]]
      name = "Zkušenosti"
      URL = "#experience"
      weight = 1

    [[languages.cs.menu.footer]]
      name = "Blog"
      URL = "#blog"
      weight = 2

    [[languages.cs.menu.footer]]
      name = "Portfolio"
      URL = "#portfolio"
      weight = 3

    [[languages.cs.menu.footer]]
      name = "Kontakt"
      URL = "#contact"
      weight = 4

# SEO defaults
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]


  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 1

  [[menu.header]]
  name = "Blog"
  URL = "#blog"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "Experience"
  URL = "#experience"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "#blog"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "values", "blog", "client-and-work", "cooperation", "contact"]

  [params.seo]
    twitter = "@pragmaxim"

  [params.logo]
    char1 = "P"
    char2 = "r"
    char3 = "a"
    char4 = "g"
    char5 = "m"
    char6 = "a"
    char7 = "x"
    char8 = "i"
    char9 = "m"

[params.footer]
      copyright = "© Pragmaxim 2023"

[markup]
  [markup.highlight]
    style = "github"
    noClasses = true
